#
# User configuration sourced by interactive shells
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias vim=nvim
alias oldvim="command vim"
alias cvim="command vim -u ~/Documents/Code/CPlusPlus/NZIC/plain_vimrc -N"
export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"
export EDITOR=nvim
export HOMEBREW_EDITOR=nvim
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Easy Markdown to Html Function
function markdown() {
    if [[ $# -eq 0 ]]; then
        echo "Markdown: markdown file is undefined"
        return 1;
    elif ls $1 1> /dev/null 2>&1; then
        pandoc -s -o $1.html $1
        return 0;
    else
        echo "Markdown: markdown file is undefined"
        return 1
    fi
}

# Play music :D
function pmusic() {
    if [[ $# -eq 0 ]]; then
        echo "Play Music: music file is undefined"
        return 1;
    else
        killall play
        play $1 -q repeat - & kill -TSTP %play
        bg %play
    fi
}

# You gotta stop the music eventually right?
function smusic() {
    killall play
}

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' file-sort access

autoload -Uz compinit
compinit
# End of lines added by compinstall

setopt extendedglob
typeset -A abbrevs
abbrevs=(
        "j" "~/CommonLinks/"
)

#create aliases for the abbrevs too
for abbr in ${(k)abbrevs}; do
   alias -g $abbr="${abbrevs[$abbr]}"
done

my-expand-abbrev() {
    local MATCH
    LBUFFER=${LBUFFER%%(#m)[_a-zA-Z0-9]#}
    command=${abbrevs[$MATCH]}
    LBUFFER+=${command:-$MATCH}

    if [[ "${command}" =~ "__CURSOR__" ]]; then
        RBUFFER=${LBUFFER[(ws:__CURSOR__:)2]}
        LBUFFER=${LBUFFER[(ws:__CURSOR__:)1]}
    else
        zle self-insert
    fi

    if [[ -n ${abbrevs[$MATCH]} ]]; then
        zle backward-char 
        zle delete-char
    fi 
}

zle -N my-expand-abbrev
bindkey "k" my-expand-abbrev
bindkey -M isearch "k" self-insert
